export const APIURL = `https://tourist-attraction.p.rapidapi.com/`;
export const APIKEY = '663abc4daamshb6288e660f99261p1d2a18jsn56dea8046688';
export const APIHOST = 'tourist-attraction.p.rapidapi.com';
export const INITIAL = ['currencies', 'languages', 'typeahead', 'search', 'detail', 'photos', 'reviews'];
// export let body = '';
export const SAMPLELANG = "language: 'en_US'";
export const SAMPLECRNCS = "currency: 'USD'";
export let NUMS = [];
export let I = "4";
